server:
  port: 9013
spring:
  application:
    name: tensquare-encrypt
  main:
    allow-bean-definition-overriding: true #遇到相同名字允许覆盖
zuul:
  routes:
    tensquare-article: #文章
      path: /article/** #配置请求URL的请求规则
      serviceId: tensquare-article #指定Eureka注册中心中的服务id
      strip-prefix: false
      sentiviteHeaders:
      customSensitiveHeaders: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
    instance:
      prefer-ip-address: true